title: 3D printing
description: >-
  The site to order prints from Evan.

baseurl: "" # repo name, leave blank for user/org pages.
url: "https://bagpipesrbetter.github.io/" # Full URL, always.

permalink: /:title

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  style: :compressed

# These won't matter for drop-in HTML replacements anyway
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
